# Generated by Django 2.1 on 2018-10-28 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotografia', models.ImageField(upload_to='photos')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('raza', models.CharField(max_length=200, verbose_name='raza')),
                ('descripcion', models.TextField(verbose_name='contenido')),
                ('estado', models.CharField(choices=[('rescatado', 'RESCATADO'), ('disponible', 'DISPONIBLE'), ('adoptado', 'ADOPTADO')], default='rescatado', max_length=50)),
            ],
        ),
    ]
