# Generated by Django 2.1 on 2018-10-28 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0002_perro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='perro',
            name='fotografia',
            field=models.ImageField(upload_to='../static/photos'),
        ),
        migrations.AlterField(
            model_name='perro',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='perro',
            name='raza',
            field=models.CharField(max_length=200, verbose_name='Raza'),
        ),
    ]
