# Generated by Django 2.1 on 2018-11-01 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0005_perro_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='autor',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
