# Generated by Django 2.1 on 2018-11-02 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0008_perro_adoptador_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='adoptador_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
