# Generated by Django 2.1 on 2018-11-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0009_auto_20181102_0542'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='blog')),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
