# Generated by Django 2.1 on 2018-11-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0010_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='subtitulo',
            field=models.CharField(max_length=200, null=True, verbose_name='Titulo'),
        ),
    ]
